application: githubgadget
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js
  
- url: /test.*
  #login: admin  # This is important if you deploy the test directory in production!
  script: gaeunit.py
  
  
- url: /gg\.html
  script: gg.py
  
- url: /dologin\.html
  script: gg.py

- url: /.*
  script: githubgadget.py