application: githubgadget
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js
  
- url: /gg\.html
  script: gg.py

- url: /.*
  script: githubgadget.py
  
  